var a;a||(a=typeof Module !== 'undefined' ? Module : {});var l={},p;for(p in a)a.hasOwnProperty(p)&&(l[p]=a[p]);a.arguments=[];a.thisProgram="./this.program";a.quit=function(b,c){throw c;};a.preRun=[];a.postRun=[];var q=!1,r=!1,v=!1,aa=!1;q="object"===typeof window;r="function"===typeof importScripts;v="object"===typeof process&&"function"===typeof require&&!q&&!r;aa=!q&&!v&&!r;var w="";function x(b){return a.locateFile?a.locateFile(b,w):w+b}
if(v){w=__dirname+"/";var y,A;a.read=function(b,c){y||(y=require("fs"));A||(A=require("path"));b=A.normalize(b);b=y.readFileSync(b);return c?b:b.toString()};a.readBinary=function(b){b=a.read(b,!0);b.buffer||(b=new Uint8Array(b));assert(b.buffer);return b};1<process.argv.length&&(a.thisProgram=process.argv[1].replace(/\\/g,"/"));a.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(b){if(!(b instanceof B))throw b;});process.on("unhandledRejection",
C);a.quit=function(b){process.exit(b)};a.inspect=function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(a.read=function(b){return read(b)}),a.readBinary=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");assert("object"===typeof b);return b},"undefined"!=typeof scriptArgs?a.arguments=scriptArgs:"undefined"!=typeof arguments&&(a.arguments=arguments),"function"===typeof quit&&(a.quit=function(b){quit(b)});else if(q||r)r?
w=self.location.href:document.currentScript&&(w=document.currentScript.src),w=0!==w.indexOf("blob:")?w.substr(0,w.lastIndexOf("/")+1):"",a.read=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},r&&(a.readBinary=function(b){var c=new XMLHttpRequest;c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),a.readAsync=function(b,c,d){var e=new XMLHttpRequest;e.open("GET",b,!0);e.responseType="arraybuffer";e.onload=function(){200==
e.status||0==e.status&&e.response?c(e.response):d()};e.onerror=d;e.send(null)},a.setWindowTitle=function(b){document.title=b};var G=a.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),H=a.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||G);for(p in l)l.hasOwnProperty(p)&&(a[p]=l[p]);l=void 0;function ba(b){var c;c||(c=16);return Math.ceil(b/c)*c}
var ca={"f64-rem":function(b,c){return b%c},"debugger":function(){debugger}},I=!1;function assert(b,c){b||C("Assertion failed: "+c)}var da="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function ea(b){for(var c=0,d=0;d<b.length;++d){var e=b.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|b.charCodeAt(++d)&1023);127>=e?++c:c=2047>=e?c+2:65535>=e?c+3:2097151>=e?c+4:67108863>=e?c+5:c+6}var g=c+1;c=ia(g);d=c;e=ja;if(0<g){g=d+g-1;for(var h=0;h<b.length;++h){var f=b.charCodeAt(h);if(55296<=f&&57343>=f){var m=b.charCodeAt(++h);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(d>=g)break;e[d++]=f}else{if(2047>=f){if(d+1>=g)break;e[d++]=192|f>>6}else{if(65535>=f){if(d+2>=g)break;e[d++]=
224|f>>12}else{if(2097151>=f){if(d+3>=g)break;e[d++]=240|f>>18}else{if(67108863>=f){if(d+4>=g)break;e[d++]=248|f>>24}else{if(d+5>=g)break;e[d++]=252|f>>30;e[d++]=128|f>>24&63}e[d++]=128|f>>18&63}e[d++]=128|f>>12&63}e[d++]=128|f>>6&63}e[d++]=128|f&63}}e[d]=0}return c}var buffer,ja,J,K;
function ka(){a.HEAP8=ja=new Int8Array(buffer);a.HEAP16=new Int16Array(buffer);a.HEAP32=K=new Int32Array(buffer);a.HEAPU8=J=new Uint8Array(buffer);a.HEAPU16=new Uint16Array(buffer);a.HEAPU32=new Uint32Array(buffer);a.HEAPF32=new Float32Array(buffer);a.HEAPF64=new Float64Array(buffer)}var N,O,P,Q,R,la,ma;N=O=P=Q=R=la=ma=0;var na=a.TOTAL_STACK||5242880,S=a.TOTAL_MEMORY||16777216;S<na&&H("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+S+"! (TOTAL_STACK="+na+")");
a.buffer?buffer=a.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(a.wasmMemory=new WebAssembly.Memory({initial:S/65536,maximum:S/65536}),buffer=a.wasmMemory.buffer):buffer=new ArrayBuffer(S),a.buffer=buffer);ka();function T(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c();else{var d=c.w;"number"===typeof d?void 0===c.j?a.dynCall_v(d):a.dynCall_vi(d,c.j):d(void 0===c.j?null:c.j)}}}var oa=[],pa=[],qa=[],ra=[],ta=[],U=!1;
function wa(){var b=a.preRun.shift();oa.unshift(b)}var V=0,xa=null,W=null;a.preloadedImages={};a.preloadedAudios={};function X(b){return String.prototype.startsWith?b.startsWith("data:application/octet-stream;base64,"):0===b.indexOf("data:application/octet-stream;base64,")}
(function(){function b(){try{if(a.wasmBinary)return new Uint8Array(a.wasmBinary);if(a.readBinary)return a.readBinary(g);throw"both async and sync fetching of the wasm failed";}catch(D){C(D)}}function c(){return a.wasmBinary||!q&&!r||"function"!==typeof fetch?new Promise(function(c){c(b())}):fetch(g,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+g+"'";return b.arrayBuffer()}).catch(function(){return b()})}function d(b){function d(b){m=b.exports;if(m.memory){b=
m.memory;var c=a.buffer;b.byteLength<c.byteLength&&H("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");c=new Int8Array(c);(new Int8Array(b)).set(c);a.buffer=buffer=b;ka()}a.asm=m;a.usingWasm=!0;V--;a.monitorRunDependencies&&a.monitorRunDependencies(V);0==V&&(null!==xa&&(clearInterval(xa),xa=null),W&&(b=W,W=null,b()))}function e(b){d(b.instance)}function h(b){c().then(function(b){return WebAssembly.instantiate(b,f)}).then(b,function(b){H("failed to asynchronously prepare wasm: "+
b);C(b)})}if("object"!==typeof WebAssembly)return H("no native wasm support detected"),!1;if(!(a.wasmMemory instanceof WebAssembly.Memory))return H("no native wasm Memory in use"),!1;b.memory=a.wasmMemory;f.global={NaN:NaN,Infinity:Infinity};f["global.Math"]=Math;f.env=b;V++;a.monitorRunDependencies&&a.monitorRunDependencies(V);if(a.instantiateWasm)try{return a.instantiateWasm(f,d)}catch(z){return H("Module.instantiateWasm callback failed with error: "+z),!1}a.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
X(g)||"function"!==typeof fetch?h(e):WebAssembly.instantiateStreaming(fetch(g,{credentials:"same-origin"}),f).then(e,function(b){H("wasm streaming compile failed: "+b);H("falling back to ArrayBuffer instantiation");h(e)});return{}}var e="index.wast",g="index.wasm",h="index.temp.asm.js";X(e)||(e=x(e));X(g)||(g=x(g));X(h)||(h=x(h));var f={global:null,env:null,asm2wasm:ca,parent:a},m=null;a.asmPreload=a.asm;var F=a.reallocBuffer;a.reallocBuffer=function(b){if("asmjs"===M)var c=F(b);else a:{var d=a.usingWasm?
65536:16777216;0<b%d&&(b+=d-b%d);d=a.buffer.byteLength;if(a.usingWasm)try{c=-1!==a.wasmMemory.grow((b-d)/65536)?a.buffer=a.wasmMemory.buffer:null;break a}catch(L){c=null;break a}c=void 0}return c};var M="";a.asm=function(b,c){if(!c.table){b=a.wasmTableSize;void 0===b&&(b=1024);var e=a.wasmMaxTableSize;c.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:b,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:b,element:"anyfunc"}):
Array(b);a.wasmTable=c.table}c.__memory_base||(c.__memory_base=a.STATIC_BASE);c.__table_base||(c.__table_base=0);c=d(c);assert(c,"no binaryen method succeeded.");return c}})();N=1024;O=N+5472;pa.push();a.STATIC_BASE=N;a.STATIC_BUMP=5472;O+=16;var ya=[null,[],[]],Y=0;function Z(){Y+=4;return K[Y-4>>2]}var za={},Aa=O;O=O+4+15&-16;ma=Aa;P=Q=ba(O);R=P+na;la=ba(R);K[ma>>2]=la;a.wasmTableSize=6;a.wasmMaxTableSize=6;a.o={};
a.s={c:C,g:function(b,c){Y=c;try{var d=za.u();Z();var e=Z(),g=Z(),h=Z();FS.A(d,e,h);K[g>>2]=d.position;d.v&&0===e&&0===h&&(d.v=null);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof FS.l||C(f),-f.m}},b:function(b,c){Y=c;try{var d=Z(),e=Z(),g=Z();for(c=b=0;c<g;c++){for(var h=K[e+8*c>>2],f=K[e+(8*c+4)>>2],m=0;m<f;m++){var F=d,M=J[h+m],D=ya[F];assert(D);if(0===M||10===M){F=1===F?G:H;a:{for(var sa=void 0,fa=void 0,L=void 0,z=void 0,E=void 0,k=void 0,t=D,u=0,n=u;t[n];)++n;if(16<n-u&&t.subarray&&
da)var ua=da.decode(t.subarray(u,n));else for(n="";;){k=t[u++];if(!k){ua=n;break a}if(k&128)if(E=t[u++]&63,192==(k&224))n+=String.fromCharCode((k&31)<<6|E);else if(z=t[u++]&63,224==(k&240)?k=(k&15)<<12|E<<6|z:(L=t[u++]&63,240==(k&248)?k=(k&7)<<18|E<<12|z<<6|L:(fa=t[u++]&63,248==(k&252)?k=(k&3)<<24|E<<18|z<<12|L<<6|fa:(sa=t[u++]&63,k=(k&1)<<30|E<<24|z<<18|L<<12|fa<<6|sa))),65536>k)n+=String.fromCharCode(k);else{var va=k-65536;n+=String.fromCharCode(55296|va>>10,56320|va&1023)}else n+=String.fromCharCode(k)}}F(ua);
D.length=0}else D.push(M)}b+=f}return b}catch(ha){return"undefined"!==typeof FS&&ha instanceof FS.l||C(ha),-ha.m}},f:function(b,c){Y=c;return 0},e:function(b,c){Y=c;try{var d=za.u();FS.close(d);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.l||C(e),-e.m}},d:function(b,c,d){J.set(J.subarray(c,c+d),b);return b},a:Q};var Ba=a.asm(a.o,a.s,buffer);a.asm=Ba;a._main=function(){return a.asm.h.apply(null,arguments)};var ia=a.stackAlloc=function(){return a.asm.i.apply(null,arguments)};
a.asm=Ba;function B(b){this.name="ExitStatus";this.message="Program terminated with exit("+b+")";this.status=b}B.prototype=Error();B.prototype.constructor=B;W=function Ca(){a.calledRun||Da();a.calledRun||(W=Ca)};
a.callMain=function(b){b=b||[];U||(U=!0,T(pa));var c=b.length+1,d=ia(4*(c+1));K[d>>2]=ea(a.thisProgram);for(var e=1;e<c;e++)K[(d>>2)+e]=ea(b[e-1]);K[(d>>2)+c]=0;try{var g=a._main(c,d,0);if(!a.noExitRuntime||0!==g){if(!a.noExitRuntime&&(I=!0,Q=void 0,T(ra),a.onExit))a.onExit(g);a.quit(g,new B(g))}}catch(h){h instanceof B||("SimulateInfiniteLoop"==h?a.noExitRuntime=!0:((b=h)&&"object"===typeof h&&h.stack&&(b=[h,h.stack]),H("exception thrown: "+b),a.quit(1,h)))}finally{}};
function Da(b){function c(){if(!a.calledRun&&(a.calledRun=!0,!I)){U||(U=!0,T(pa));T(qa);if(a.onRuntimeInitialized)a.onRuntimeInitialized();a._main&&Ea&&a.callMain(b);if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();ta.unshift(c)}T(ta)}}b=b||a.arguments;if(!(0<V)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)wa();T(oa);0<V||a.calledRun||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},
1);c()},1)):c())}}a.run=Da;function C(b){if(a.onAbort)a.onAbort(b);void 0!==b?(G(b),H(b),b=JSON.stringify(b)):b="";I=!0;throw"abort("+b+"). Build with -s ASSERTIONS=1 for more info.";}a.abort=C;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();var Ea=!0;a.noInitialRun&&(Ea=!1);a.noExitRuntime=!0;Da();
